/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#4cd6ff",
        "on-surface": "#e1e2eb",
        "surface-dim": "#10131a",
        "on-secondary": "#390093",
        "surface-bright": "#363940",
        "background": "#10131a",
        "primary": "#c0c1ff",
        "surface-container-highest": "#32353c",
        "on-error": "#690005",
        "tertiary-fixed": "#b7eaff",
        "on-secondary-container": "#c8b4ff",
        "on-secondary-fixed": "#21005d",
        "primary-fixed-dim": "#c0c1ff",
        "secondary": "#cebdff",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#004e60",
        "error": "#ffb4ab",
        "surface-container-low": "#191c22",
        "on-background": "#e1e2eb",
        "on-primary-container": "#0d0096",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-primary-fixed": "#07006c",
        "outline": "#908fa0",
        "surface-tint": "#c0c1ff",
        "surface-variant": "#32353c",
        "error-container": "#93000a",
        "inverse-surface": "#e1e2eb",
        "primary-fixed": "#e1e0ff",
        "outline-variant": "#464554",
        "surface-container-high": "#272a31",
        "secondary-fixed-dim": "#cebdff",
        "surface-container-lowest": "#0b0e14",
        "secondary-fixed": "#e8ddff",
        "on-primary": "#1000a9",
        "on-tertiary": "#003543",
        "tertiary": "#4cd6ff",
        "on-tertiary-container": "#002e3a",
        "on-tertiary-fixed": "#001f28",
        "surface-container": "#1d2026",
        "on-secondary-fixed-variant": "#5300cd",
        "secondary-container": "#5a01df",
        "tertiary-container": "#009dc1",
        "on-surface-variant": "#c7c4d7",
        "primary-container": "#8083ff",
        "inverse-on-surface": "#2e3037",
        "surface": "#10131a",
        "inverse-primary": "#494bd6",
      },
      fontFamily: {
        headline: ["Inter Tight", "Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
